/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airport_bill;

import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import java.sql.*;
import java.text.SimpleDateFormat;

import javax.swing.JOptionPane;

public final class flightprice extends javax.swing.JFrame {

    DefaultComboBoxModel cbb = new DefaultComboBoxModel();
    DefaultComboBoxModel flightMOdel = new DefaultComboBoxModel();
    public String lpb;
    public String id;
    public int price;
    public String name;
    public String surname;
    public String idowner;
    public String nation;

    public int s;

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    Connection c = Airport_bill.getcon();

    public void addcombobox() {
        String[] unit = {"normal", "high"};
        seatclasscb.removeAllItems();
        for (String s : unit) {
            seatclasscb.addItem(s);
        }
    }

    public void addcombobox2() {
        String[] time = {
            "3:00", "8:00", "9:00", "10:00", "13:00", "17:00", "20:00"
        };
        time1.removeAllItems();
        for (String o : time) {
            time1.addItem(o);
        }

    }

    public flightprice(String id, String lpb, int price) {
        this.id = id;
        this.lpb = lpb;
        this.price = price;

        initComponents();
        time1.setModel(flightMOdel);
        seatclasscb.setModel(cbb);
        addcombobox();
        logo();
        addcombobox2();

    }

    public flightprice(String id, String lpb, int price, String name, String surname, String idowner, String nation) {
        initComponents();
        time1.setModel(flightMOdel);
        seatclasscb.setModel(cbb);
        addcombobox();
        logo();
        addcombobox2();
        this.id = id;
        this.lpb = lpb;
        this.price = price;
        this.name = name;
        this.surname = surname;
        this.idowner = idowner;
        this.nation = nation;

    }

    public flightprice() {
        initComponents();
        time1.setModel(flightMOdel);
        seatclasscb.setModel(cbb);
        addcombobox();
        logo();
        addcombobox2();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        seatclasscb = new javax.swing.JComboBox<>();
        logopic = new javax.swing.JLabel();
        piceaddtion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsurname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        time1 = new javax.swing.JComboBox<>();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        wheretogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seatclasscb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(seatclasscb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 110, -1));

        logopic.setText("jLabel2");
        jPanel2.add(logopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 17, 158, 88));

        piceaddtion.setText("100.000 Kip");
        jPanel2.add(piceaddtion, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 101, 82, -1));

        jLabel1.setText("Date");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 60, -1));

        txtname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnameMouseClicked(evt);
            }
        });
        jPanel2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 17, 218, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 17, 117, 22));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Surname");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 58, 117, 22));

        txtsurname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel2.add(txtsurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 58, 218, -1));

        jButton1.setText("Finish");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 325, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 325, -1, -1));

        jCheckBox2.setText("Addition service");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 99, 117, -1));

        jLabel4.setText("Seat class");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 140, 117, -1));

        time1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 110, -1));
        jPanel2.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 110, -1));

        jLabel5.setText("Time");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 117, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 580, 370));

        wheretogo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        wheretogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(wheretogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 310, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        wheretogo.setText(lpb);
        txtname.setText(name);
        txtsurname.setText(surname);

    }//GEN-LAST:event_formWindowOpened

    private void txtnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnameMouseClicked
        if (evt.getClickCount() == 2) {
            bill_owner bon = new bill_owner(id, lpb, price);
            bon.show();
            dispose();
        }
    }//GEN-LAST:event_txtnameMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        fligth f = new fligth();
        f.id = id;
        dispose();
        f.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    int point1;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int jop = JOptionPane.showConfirmDialog(this, "Do you agree to this order?", "I confrim", JOptionPane.YES_NO_CANCEL_OPTION);
        if (jop == 0) {
            if (jCheckBox2.isSelected() == true) {
                addition = "T";
                p = 100000;
            }

            try {
                String sql = "select * from accout where c_id=?";
                PreparedStatement psm = c.prepareStatement(sql);
                psm.setString(1, id);
                ResultSet rs = psm.executeQuery();
                if (rs.next()) {
                    int point = Integer.parseInt(rs.getString("c_point"));
                    point1 = point;
                    if (point == 100) {
                        point = 0;
                    } else {
                        point++;
                    }
                    sql = "update accout set c_point=? where c_id=?";
                    PreparedStatement psn = c.prepareStatement(sql);
                    psn.setString(1, String.valueOf(point));
                    psn.setString(2, id);
                    psn.executeUpdate();
                }

                int sc = 0;
                if (seatclasscb.getSelectedItem().equals("high")) {
                    float seat = (float) 0.5;
                    sc = (int) (price * seat);
                }
                price = price + sc + p;

                sql = "insert into detail values(?,?,?,?,?,?,?,?,?)";
                PreparedStatement pst = c.prepareStatement(sql);
                pst.setString(1, null);
                pst.setString(2, idowner);
                pst.setString(3, id);
                pst.setString(4, lpb);
                pst.setString(5, addition);
                pst.setString(6, seatclasscb.getSelectedItem().toString());
                pst.setString(7, time1.getSelectedItem().toString());
                pst.setString(8, String.valueOf(price));
                String date = sdf.format(jDateChooser2.getDate());
                pst.setString(9, date);
                if (pst.executeUpdate() == 1) {
                    if (point1 == 100) {
                        JOptionPane.showMessageDialog(this, "free ticket");
                        price = 0;
                    }
                    JOptionPane.showMessageDialog(this, "done");
                    bill b = new bill();
                    b.id = id;
                    b.addition = addition;
                    b.datee = date;
                    b.clas = seatclasscb.getSelectedItem().toString();
                    b.time = time1.getSelectedItem().toString();
                    b.lpb = lpb;
                    b.name = name;
                    b.surname = surname;
                    b.nation = nation;
                    b.price = price;
                    b.surname = surname;
                    b.show();
                    txtname.setText("");
                    txtsurname.setText("");
                    jCheckBox2.setSelected(false);
                    seatclasscb.setSelectedIndex(-1);
                    time1.setSelectedIndex(-1);

                    dispose();

                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    String addition = "F";
    int p = 0;
    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed

    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(flightprice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(flightprice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(flightprice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(flightprice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new flightprice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox2;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logopic;
    private javax.swing.JLabel piceaddtion;
    private javax.swing.JComboBox<String> seatclasscb;
    private javax.swing.JComboBox<String> time1;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsurname;
    private javax.swing.JLabel wheretogo;
    // End of variables declaration//GEN-END:variables
}
