/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airport_bill;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VSOA
 */
public class History extends javax.swing.JFrame {

    public String id;
    /**
     * Creates new form History
     */
    Connection c = Airport_bill.getcon();
    DefaultTableModel model = new DefaultTableModel();
    
    public History() {
        initComponents();
        model = (DefaultTableModel) show.getModel();

    }

    public void show(String id) {
        try {
            int idx = show.getRowCount() - 1;
            while (idx >= 0) {
                model.removeRow(idx--);
            }
            String sql = "SELECT  owner.o_name,owner.o_surname,owner.o_nationality,"
                    + "owner.o_telephone,owner.o_p,owner.o_d,owner.o_v,  airline, "
                    + "addition, seat, flight, price, date FROM detail\n"
                    + "INNER JOIN owner ON owner.o_id=detail.o_id\n"
                    + "WHERE detail.c_id=?";
            PreparedStatement pst = c.prepareStatement(sql);
            pst.clearParameters();
            pst.setString(1, id);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String[] itm = {
                    rs.getString("owner.o_name"),
                    rs.getString("owner.o_surname"),
                    rs.getString("owner.o_nationality"),
                    rs.getString("owner.o_telephone"),
                    rs.getString("owner.o_p"),
                    rs.getString("owner.o_d"),
                    rs.getString("owner.o_v"),
                    rs.getString("detail.airline"),
                    rs.getString("detail.addition"),
                    rs.getString("detail.seat"),
                    rs.getString("detail.flight"),
                    rs.getString("detail.date"),
                    rs.getString("detail.price")

                };
                model.addRow(itm);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        backbt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        show = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backbt.setText("Back");
        backbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtActionPerformed(evt);
            }
        });
        jPanel2.add(backbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "surname", "nationality", "telephone", "province", "district", "village", "airline", "addition", "seat", "time", "date", "price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(show);
        if (show.getColumnModel().getColumnCount() > 0) {
            show.getColumnModel().getColumn(0).setPreferredWidth(50);
            show.getColumnModel().getColumn(1).setPreferredWidth(70);
            show.getColumnModel().getColumn(2).setPreferredWidth(20);
            show.getColumnModel().getColumn(3).setPreferredWidth(50);
            show.getColumnModel().getColumn(4).setPreferredWidth(40);
            show.getColumnModel().getColumn(5).setPreferredWidth(40);
            show.getColumnModel().getColumn(6).setPreferredWidth(40);
            show.getColumnModel().getColumn(7).setPreferredWidth(120);
            show.getColumnModel().getColumn(8).setPreferredWidth(20);
            show.getColumnModel().getColumn(9).setPreferredWidth(30);
            show.getColumnModel().getColumn(10).setPreferredWidth(30);
            show.getColumnModel().getColumn(11).setPreferredWidth(30);
            show.getColumnModel().getColumn(12).setPreferredWidth(60);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1080, 320));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel1.setText("History");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 140, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        show(id);

    }//GEN-LAST:event_formWindowOpened

    private void backbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_backbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable show;
    // End of variables declaration//GEN-END:variables
}
